import type { ThemePreset } from './types';

export const themePresets: ThemePreset[] = [
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Clean, clean layout with lots of white space and crisp typography.',
    config: {
      primaryColor: '#0F172A',
      secondaryColor: '#64748B',
      accentColor: '#0F172A',
      backgroundColor: '#FAFAFA',
      cardColor: '#FFFFFF',
      buttonColor: '#0F172A',
      textColor: '#1E293B',
      fontFamily: 'Inter, sans-serif',
      fontSizeScale: 1.0,
      cardRadius: '8px',
      buttonStyle: 'rounded',
      sectionSpacing: 'comfortable',
      categoryStyle: 'underline',
      itemCardStyle: 'comfortable',
      headerStyle: 'classic',
      bannerStyle: 'compact',
      logoStyle: 'rounded-square',
      shadowStyle: 'soft',
      dividerStyle: 'solid',
      animationLevel: 'subtle',
    },
  },
  {
    id: 'luxury',
    name: 'Luxury',
    description: 'Deep royal blue, soft gold details, and clean modern card styling.',
    config: {
      primaryColor: '#1E1B4B',
      secondaryColor: '#B45309',
      accentColor: '#D97706',
      backgroundColor: '#FAF9F6',
      cardColor: '#FFFFFF',
      buttonColor: '#1E1B4B',
      textColor: '#1E1B4B',
      fontFamily: 'Outfit, Georgia, serif',
      fontSizeScale: 1.05,
      cardRadius: '16px',
      buttonStyle: 'pill',
      sectionSpacing: 'luxury',
      categoryStyle: 'pills',
      itemCardStyle: 'luxury',
      headerStyle: 'modern',
      bannerStyle: 'large',
      logoStyle: 'circle',
      shadowStyle: 'strong',
      dividerStyle: 'dashed',
      animationLevel: 'subtle',
    },
  },
  {
    id: 'modern',
    name: 'Modern',
    description: 'Sleek and tech-forward layout utilizing sharp contrast and cool colors.',
    config: {
      primaryColor: '#2563EB',
      secondaryColor: '#475569',
      accentColor: '#3B82F6',
      backgroundColor: '#F8FAFC',
      cardColor: '#FFFFFF',
      buttonColor: '#2563EB',
      textColor: '#0F172A',
      fontFamily: 'Roboto, sans-serif',
      fontSizeScale: 1.0,
      cardRadius: '12px',
      buttonStyle: 'rounded',
      sectionSpacing: 'comfortable',
      categoryStyle: 'chips',
      itemCardStyle: 'comfortable',
      headerStyle: 'classic',
      bannerStyle: 'compact',
      logoStyle: 'rounded-square',
      shadowStyle: 'soft',
      dividerStyle: 'solid',
      animationLevel: 'subtle',
    },
  },
  {
    id: 'cafe',
    name: 'Cafe Wood',
    description: 'Earthy cream backgrounds, rich chocolate text, and friendly round pills.',
    config: {
      primaryColor: '#451A03',
      secondaryColor: '#B45309',
      accentColor: '#D97706',
      backgroundColor: '#FAF7F2',
      cardColor: '#FFFFFF',
      buttonColor: '#451A03',
      textColor: '#451A03',
      fontFamily: 'Outfit, sans-serif',
      fontSizeScale: 1.0,
      cardRadius: '16px',
      buttonStyle: 'pill',
      sectionSpacing: 'comfortable',
      categoryStyle: 'pills',
      itemCardStyle: 'comfortable',
      headerStyle: 'centered',
      bannerStyle: 'compact',
      logoStyle: 'circle',
      shadowStyle: 'soft',
      dividerStyle: 'solid',
      animationLevel: 'subtle',
    },
  },
  {
    id: 'indian',
    name: 'Indian Restaurant',
    description: 'Rich royal saffron and deep green borders giving a warm traditional vibe.',
    config: {
      primaryColor: '#B45309',
      secondaryColor: '#15803D',
      accentColor: '#EA580C',
      backgroundColor: '#FFFDF9',
      cardColor: '#FFFFFF',
      buttonColor: '#B45309',
      textColor: '#451A03',
      fontFamily: 'Outfit, serif',
      fontSizeScale: 1.05,
      cardRadius: '12px',
      buttonStyle: 'rounded',
      sectionSpacing: 'luxury',
      categoryStyle: 'cards',
      itemCardStyle: 'luxury',
      headerStyle: 'modern',
      bannerStyle: 'large',
      logoStyle: 'circle',
      shadowStyle: 'soft',
      dividerStyle: 'solid',
      animationLevel: 'subtle',
    },
  },
  {
    id: 'fine-dining',
    name: 'Fine Dining',
    description: 'Luxurious burgundy and serif elegance, fit for Michelin star aesthetics.',
    config: {
      primaryColor: '#881337',
      secondaryColor: '#9A3412',
      accentColor: '#BE123C',
      backgroundColor: '#FCFBFA',
      cardColor: '#FFFFFF',
      buttonColor: '#881337',
      textColor: '#1F2937',
      fontFamily: 'Georgia, serif',
      fontSizeScale: 1.1,
      cardRadius: '4px',
      buttonStyle: 'square',
      sectionSpacing: 'luxury',
      categoryStyle: 'underline',
      itemCardStyle: 'luxury',
      headerStyle: 'centered',
      bannerStyle: 'large',
      logoStyle: 'square',
      shadowStyle: 'soft',
      dividerStyle: 'solid',
      animationLevel: 'none',
    },
  },
  {
    id: 'dark',
    name: 'Modern Dark',
    description: 'Immersive slate dark mode with glowing sky-blue action accents.',
    config: {
      primaryColor: '#38BDF8',
      secondaryColor: '#94A3B8',
      accentColor: '#0EA5E9',
      backgroundColor: '#0F172A',
      cardColor: '#1E293B',
      buttonColor: '#0284C7',
      textColor: '#F8FAFC',
      fontFamily: 'Inter, sans-serif',
      fontSizeScale: 1.0,
      cardRadius: '12px',
      buttonStyle: 'rounded',
      sectionSpacing: 'comfortable',
      categoryStyle: 'pills',
      itemCardStyle: 'comfortable',
      headerStyle: 'modern',
      bannerStyle: 'compact',
      logoStyle: 'circle',
      shadowStyle: 'none',
      dividerStyle: 'none',
      animationLevel: 'subtle',
    },
  },
  {
    id: 'orange',
    name: 'Tangerine Orange',
    description: 'Vibrant orange tags and warm grey containers for high-energy fast services.',
    config: {
      primaryColor: '#EA580C',
      secondaryColor: '#4B5563',
      accentColor: '#F97316',
      backgroundColor: '#FFFBEB',
      cardColor: '#FFFFFF',
      buttonColor: '#EA580C',
      textColor: '#1F2937',
      fontFamily: 'Inter, sans-serif',
      fontSizeScale: 1.0,
      cardRadius: '16px',
      buttonStyle: 'pill',
      sectionSpacing: 'comfortable',
      categoryStyle: 'chips',
      itemCardStyle: 'comfortable',
      headerStyle: 'classic',
      bannerStyle: 'compact',
      logoStyle: 'rounded-square',
      shadowStyle: 'soft',
      dividerStyle: 'solid',
      animationLevel: 'subtle',
    },
  },
  {
    id: 'green',
    name: 'Fresh Green',
    description: 'Clean organic vibe with fresh leaf-green buttons and clean borders.',
    config: {
      primaryColor: '#16A34A',
      secondaryColor: '#4B5563',
      accentColor: '#22C55E',
      backgroundColor: '#F0FDF4',
      cardColor: '#FFFFFF',
      buttonColor: '#16A34A',
      textColor: '#111827',
      fontFamily: 'Inter, sans-serif',
      fontSizeScale: 1.0,
      cardRadius: '12px',
      buttonStyle: 'rounded',
      sectionSpacing: 'comfortable',
      categoryStyle: 'pills',
      itemCardStyle: 'comfortable',
      headerStyle: 'classic',
      bannerStyle: 'compact',
      logoStyle: 'rounded-square',
      shadowStyle: 'soft',
      dividerStyle: 'solid',
      animationLevel: 'subtle',
    },
  },
  {
    id: 'fast-food',
    name: 'Fast Food',
    description: 'Energetic mustard yellow and red accents with round pill action badges.',
    config: {
      primaryColor: '#DC2626',
      secondaryColor: '#EAB308',
      accentColor: '#DC2626',
      backgroundColor: '#FEF2F2',
      cardColor: '#FFFFFF',
      buttonColor: '#DC2626',
      textColor: '#111827',
      fontFamily: 'Outfit, sans-serif',
      fontSizeScale: 1.0,
      cardRadius: '24px',
      buttonStyle: 'pill',
      sectionSpacing: 'compact',
      categoryStyle: 'pills',
      itemCardStyle: 'compact',
      headerStyle: 'modern',
      bannerStyle: 'compact',
      logoStyle: 'circle',
      shadowStyle: 'strong',
      dividerStyle: 'none',
      animationLevel: 'subtle',
    },
  },
  {
    id: 'bakery',
    name: 'Bakery Pink',
    description: 'Soft rose tones and friendly round corners for bakery and sweet shops.',
    config: {
      primaryColor: '#DB2777',
      secondaryColor: '#BE185D',
      accentColor: '#EC4899',
      backgroundColor: '#FDF2F8',
      cardColor: '#FFFFFF',
      buttonColor: '#DB2777',
      textColor: '#374151',
      fontFamily: 'Outfit, sans-serif',
      fontSizeScale: 1.0,
      cardRadius: '16px',
      buttonStyle: 'pill',
      sectionSpacing: 'comfortable',
      categoryStyle: 'pills',
      itemCardStyle: 'comfortable',
      headerStyle: 'centered',
      bannerStyle: 'compact',
      logoStyle: 'circle',
      shadowStyle: 'soft',
      dividerStyle: 'solid',
      animationLevel: 'subtle',
    },
  },
];
